CREATE TABLE scans (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  lastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  url VARCHAR(255) NOT NULL,
  realm VARCHAR(100) NOT NULL,
  origin CHAR(4) NOT NULL
);
